# This file contains values from Cookiecutter

default_context:
  project_name: "ubuntu-namer"
  project_description: "Python port of ubuntu-name-generator"
  organization: "ubuntu-namer"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "crypdick"
  email: "public@richarddecal.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
